---
title: "eechidna: Exploring Australian Election and Census Data"
author:
  - name: Dianne Cook
    affiliation: Monash University
    address:
    - Department of Econometrics and Business Statistics
    - Clayton, VIC 3800
    email:  dicook@monash.edu
  - name: Rob J Hyndman
    affiliation: Monash University
    address:
    - Department of Econometrics and Business Statistics
    - Clayton, VIC 3800
    email:  Rob.Hyndman@monash.edu
abstract: >
  An abstract of less than 150 words.
preamble: >
  % Any extra latex you need in the preamble
output: rticles::rjournal_article
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE, messages=FALSE, warning=FALSE)
# Make sure you have rticles installed.
library(eechidna)
library(ggplot2)
```

## Introduction

Introductory section which may include references in parentheses
\citep{R}, or cite a reference such as \citet{R} in the text.


## Summary

This file is only a basic article template. For full details of _The R Journal_ style and information on how to prepare your article for submission, see the [Instructions for Authors](https://journal.r-project.org/share/author-guide.pdf).


#Introduction


The R package `eechidna` provides data from the 2013 and 2016 Australian Federal Elections and 2011 and 2016 Australian Censuses for each House of Representatives electorate, along with some tools for visualizing and analysing the data.

This package was developed during the rOpenSci auunconf event in Brisbane, Queensland, during 21-22 April 2016. Peter Ellis' work on the NZ electoral data was an important inspiration for this pack


R journal



Intro about purpose

Data
 - raw and processed



Examples. Take from vignettes

Shiny web app


Discussion about difficulties and futrue development

- what aec and abs could do better
- updating for future elections and censuses
- how this might be used



\bibliography{RJreferences}
